version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: botdb_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: botdbcont
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8 
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d botdbcont"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__PostgreSQL=Host=db;Database=botdbcont;Username=postgres;Password=postgres;Port=5432
    restart: unless-stopped
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

volumes:
  postgres_data: